In [4]:
import pandas as pd
import numpy as np
import sqlite3
import streamlit

In [5]:
import utils.queries as qs

In [8]:
df_ = qs.get_flats_for_sale()
df_

,index,title,price,price_per_m2,sqrmeter,rooms,floor,page,street,location,max_floor,RefreshYearWeek,link
0,0,Atrakcyjne mieszkanie w stanie deweloperskim**...,935000.0,13883.0,67,3,3.0,0,Zygmunta Glogera,Prądnik Biały,3.0,2025-45,None
1,1,Mieszkanie na sprzedaż,892788.0,17700.0,50,3,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
2,2,NOWY Luksusowy Apartament - gotowy do wejścia ...,2250000.0,19068.0,118,4,1.0,0,Zakrzowiecka,Zwierzyniec,2.0,2025-45,None
3,3,Mieszkanie na sprzedaż,1470350.0,17500.0,84,4,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
4,4,**Atrakcyjne**do Wejścia**Stare Miasto**,1694000.0,22000.0,77,2,1.0,0,Tarłowska,Stare Miasto,5.0,2025-45,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53672,16999,Lokale i mieszkania na sprzedaż – nowa inwestycja,423453.0,15585.0,27,1,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53673,17000,Lokale i mieszkania na sprzedaż – nowa inwestycja,434402.0,15941.0,27,1,4,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53674,17001,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53675,17002,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53676,17003,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...

In [20]:
df_[df_['RefreshYearWeek']=='2025-45'].groupby(by='location')['price_per_m2'].median().round(2)

location
Azory                13592.0
Bielany              12903.0
Bieńczyce            14106.0
Bieżanów             13625.0
Bieżanów-Prokocim    13783.0
                      ...
małopolskie          15727.5
Łagiewniki           16000.0
Łobzów               18629.0
Łęg                  15642.5
Żabiniec             15523.5
Name: price_per_m2, Length: 118, dtype: float64

In [25]:
df_[df_['RefreshYearWeek']=='2026-08'].groupby(by='location')['price_per_m2'].median().round(2)

location
Azory                       15852.00
Bielany                     13734.00
Bieńczyce                   13909.00
Bieżanów                    13225.66
Bieżanów-Prokocim           14200.00
                              ...
Łagiewniki                  15254.00
Łagiewniki-Borek Fałęcki    15794.00
Łobzów                      20000.00
Łęg                         13362.00
Żabiniec                    15190.50
Name: price_per_m2, Length: 118, dtype: float64

In [19]:
df_[df_['RefreshYearWeek']=='2026-06'].groupby(by='location')['price_per_m2'].median().round(2)

location
Azory                       16491.50
Bielany                     13734.00
Bieńczyce                   13804.17
Bieżanów                    12951.33
Bieżanów-Prokocim           13763.00
                              ...
Łagiewniki                  15254.12
Łagiewniki-Borek Fałęcki    15800.00
Łobzów                      20250.00
Łęg                         15431.00
Żabiniec                    17610.00
Name: price_per_m2, Length: 111, dtype: float64

In [ ]:
df_.groupby(by='district')['price_per_m2'].mean().round(2)

In [2]:
conn = sqlite3.connect("db/users_.db")

try:
    df = pd.read_sql_query("SELECT * FROM Flat_for_Sale", conn)
except:
    df = 'nope'

conn.close()
df

'nope'

In [3]:
pd.read_sql_query("SELECT * FROM Flat_for_Sale", conn)

NameError: name 'pd' is not defined

In [69]:
df.drop_duplicates(subset=['title','sqrmeter','rooms','floor','max_floor'])

,index,title,price,price_per_m2,sqrmeter,rooms,floor,page,street,location,max_floor,RefreshYearWeek,link
0,0,Atrakcyjne mieszkanie w stanie deweloperskim**...,935000.0,13883.0,67,3,3.0,0,Zygmunta Glogera,Prądnik Biały,3.0,2025-45,None
1,1,Mieszkanie na sprzedaż,892788.0,17700.0,50,3,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
2,2,NOWY Luksusowy Apartament - gotowy do wejścia ...,2250000.0,19068.0,118,4,1.0,0,Zakrzowiecka,Zwierzyniec,2.0,2025-45,None
3,3,Mieszkanie na sprzedaż,1470350.0,17500.0,84,4,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
4,4,**Atrakcyjne**do Wejścia**Stare Miasto**,1694000.0,22000.0,77,2,1.0,0,Tarłowska,Stare Miasto,5.0,2025-45,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53669,16996,Stare Podgórze - Św Kingi! Wynajęte-świetna op...,530000.0,17608.0,30,1,4,198,Świętej Kingi,Podgórze Stare,4.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53670,16997,Lokale na sprzedaż – nowa inwestycja,406862.0,15511.0,26,1,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53671,16998,Lokale i mieszkania na sprzedaż – nowa inwestycja,411615.0,15621.0,26,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53673,17000,Lokale i mieszkania na sprzedaż – nowa inwestycja,434402.0,15941.0,27,1,4,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53674,17001,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...

In [73]:
df.dropna(subset=['price'])

,index,title,price,price_per_m2,sqrmeter,rooms,floor,page,street,location,max_floor,RefreshYearWeek,link
0,0,Atrakcyjne mieszkanie w stanie deweloperskim**...,935000.0,13883.0,67,3,3.0,0,Zygmunta Glogera,Prądnik Biały,3.0,2025-45,None
1,1,Mieszkanie na sprzedaż,892788.0,17700.0,50,3,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
2,2,NOWY Luksusowy Apartament - gotowy do wejścia ...,2250000.0,19068.0,118,4,1.0,0,Zakrzowiecka,Zwierzyniec,2.0,2025-45,None
3,3,Mieszkanie na sprzedaż,1470350.0,17500.0,84,4,2.0,0,Jerozolimska,Podgórze,6.0,2025-45,None
4,4,**Atrakcyjne**do Wejścia**Stare Miasto**,1694000.0,22000.0,77,2,1.0,0,Tarłowska,Stare Miasto,5.0,2025-45,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53672,16999,Lokale i mieszkania na sprzedaż – nowa inwestycja,423453.0,15585.0,27,1,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53673,17000,Lokale i mieszkania na sprzedaż – nowa inwestycja,434402.0,15941.0,27,1,4,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53674,17001,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53675,17002,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...
53676,17003,Lokale i mieszkania na sprzedaż – nowa inwestycja,572665.0,15711.0,36,2,5,198,Fabryczna,Grzegórzki Stare,8.0,2026-08,https://gratka.pl/nieruchomosci/mieszkanie-kra...

In [76]:
df_duplicated = df.dropna(subset=['price'])[df.dropna(subset=['price']).duplicated(subset=['title','sqrmeter','rooms','floor','max_floor','location'])]

In [82]:
df_duplicated.sort_values('price')

,index,title,price,price_per_m2,sqrmeter,rooms,floor,page,street,location,max_floor,RefreshYearWeek,link
26456,6151,KAWALERKA KOZLOWEK OD ZARAZ- WYNAJEM OKAZJONAL...,1200.0,50.0,24.0,1,1,185,Na Kozłówce,Podgórze,4.0,2026-06,https://gratka.pl/nieruchomosci/mieszkanie-kra...
26786,6481,Spacious 1-Bedroom with Open Kitchen & Dining ...,4200.0,89.0,47.0,2,1,194,Bernardyńska,Kraków,2.0,2026-06,https://gratka.pl/nieruchomosci/mieszkanie-mal...
37807,1134,Mieszkanie / 159 tys zł/ Blisko Tramwaj/ Bieżanów,159000.0,13140.0,12.1,None,parter,35,None,Bieżanów-Prokocim,NaN,2026-08,otodom.pl/pl/oferta/mieszkanie-159-tys-zl-blis...
38271,1598,Mieszkanie / 159 tys zł/ Blisko Tramwaj/ Bieżanów,159000.0,13140.0,12.1,None,parter,53,None,Bieżanów-Prokocim,NaN,2026-08,otodom.pl/pl/oferta/mieszkanie-159-tys-zl-blis...
44311,7638,Mieszkanie / 159 tys zł/ Blisko Tramwaj/ Bieżanów,159000.0,13140.0,12.1,None,parter,261,None,Bieżanów-Prokocim,NaN,2026-08,otodom.pl/pl/oferta/mieszkanie-159-tys-zl-blis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23926,3621,Penthouse w sercu Krakowa z widokiem na Wisłę,13475028.0,79800.0,168.0,3,5,112,Tadeusza Kościuszki,Salwator,5.0,2026-06,https://gratka.pl/nieruchomosci/mieszkanie-kra...
44022,7349,Penthouse w sercu Krakowa z widokiem na Wisłę,13475028.0,79800.0,168.86,None,5,249,None,Zwierzyniec,NaN,2026-08,otodom.pl/hpr/pl/oferta/penthouse-w-sercu-krak...
33890,13585,Wyjątkowy apartament z widokiem na Wisłę i Wawel!,13475028.0,79800.0,168.86,None,5,310,None,Zwierzyniec,NaN,2026-06,otodom.pl/pl/oferta/wyjatkowy-apartament-z-wid...
20973,668,Ultra-luksusowy penthouse pod Wawelem,13500000.0,53360.0,253.0,5,4,19,Koletek,Stare Miasto,4.0,2026-06,https://gratka.pl/nieruchomosci/mieszkanie-kra...
34995,14690,Ultra-luksusowy penthouse pod Wawelem,13500000.0,53360.0,253.0,None,4,340,None,Stare Miasto,NaN,2026-06,otodom.pl/pl/oferta/ultra-luksusowy-penthouse-...

In [34]:
df.columns

Index(['index', 'title', 'price', 'price_per_m2', 'sqrmeter', 'rooms', 'floor',
       'page', 'street', 'location', 'max_floor', 'RefreshYearWeek', 'link'],
      dtype='object')

In [21]:
df = pd.read_csv('Kraków_flats_2026-02-25.csv')

In [22]:
df

,title,location,price,price_per_m2,sqrmeter,floor,link,page,rooms,street,max_floor,RefreshYearWeek
0,2-pokojowe mieszkanie 47m2 + loggia Bez Prowizji,Dębniki,710850.0,15000.0,47.39,1,otodom.pl/pl/oferta/2-pokojowe-mieszkanie-47m2...,1,NaN,NaN,NaN,2026-08
1,2-pokojowe mieszkanie 36m2 + balkon Bez Prowizji,Prądnik Biały,598373.0,16300.0,36.71,1,otodom.pl/pl/oferta/2-pokojowe-mieszkanie-36m2...,1,NaN,NaN,NaN,2026-08
2,Mieszkanie na start|2 pokoje|5.piętro ostatnie...,Prądnik Biały,686000.0,19656.0,34.9,5,otodom.pl/pl/oferta/mieszkanie-na-start-2-poko...,1,NaN,NaN,NaN,2026-08
3,Przestronne mieszkanie | Patio | -40 000 Pln,Łagiewniki-Borek Fałęcki,1060000.0,17981.0,58.95,4,otodom.pl/pl/oferta/przestronne-mieszkanie-pat...,1,NaN,NaN,NaN,2026-08
4,Mazowiecka 15 • piękna kamienica • wysoki stan...,Krowodrza,1895000.0,19297.0,98.2,parter,otodom.pl/pl/oferta/mazowiecka-15-piekna-kamie...,1,NaN,NaN,NaN,2026-08
...,...,...,...,...,...,...,...,...,...,...,...,...
16999,Lokale i mieszkania na sprzedaż – nowa inwestycja,Grzegórzki Stare,423453.0,15585.0,27,5,https://gratka.pl/nieruchomosci/mieszkanie-kra...,198,1,Fabryczna,8.0,2026-08
17000,Lokale i mieszkania na sprzedaż – nowa inwestycja,Grzegórzki Stare,434402.0,15941.0,27,4,https://gratka.pl/nieruchomosci/mieszkanie-kra...,198,1,Fabryczna,8.0,2026-08
17001,Lokale i mieszkania na sprzedaż – nowa inwestycja,Grzegórzki Stare,572665.0,15711.0,36,5,https://gratka.pl/nieruchomosci/mieszkanie-kra...,198,2,Fabryczna,8.0,2026-08
17002,Lokale i mieszkania na sprzedaż – nowa inwestycja,Grzegórzki Stare,572665.0,15711.0,36,5,https://gratka.pl/nieruchomosci/mieszkanie-kra...,198,2,Fabryczna,8.0,2026-08
17003,Lokale i mieszkania na sprzedaż – nowa inwestycja,Grzegórzki Stare,572665.0,15711.0,36,5,https://gratka.pl/nieruchomosci/mieszkanie-kra...,198,2,Fabryczna,8.0,2026-08

### Post Data

In [23]:
conn = sqlite3.connect("db/users_.db")
df.to_sql(name='Flat_for_Sale', con=conn, if_exists='append')
conn.close()

### Delete Data (observation at a time)

In [27]:
sql = 'DELETE FROM Flats_for_Sale WHERE sqrmeter = ?'
conn = sqlite3.connect("db/users_.db")
cur = conn.cursor()
cur.execute(sql, ('Szlak,'))
conn.commit()
conn.close()

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 6 supplied.

In [7]:
import sqlite3

delete_stmt = 'DELETE FROM Flats_for_Sale WHERE RefreshYearWeek = ?'

try:
    with sqlite3.connect("db/users_.db") as conn:
        cur = conn.cursor()
        cur.execute(delete_stmt, ('2026-08',))
        conn.commit()
except sqlite3.OperationalError as e:
    print(e)

In [14]:
con = sqlite3.connect("db/users_.db")
df = pd.read_sql_query('SELECT * FROM Flat_for_Sale', con)

In [19]:
df_rec = pd.read_csv('Kraków_flats_2026-02-25.csv')

In [20]:
df = df[df['RefreshYearWeek']!= '2026-08']

In [22]:
df = pd.concat([df,df_rec])

In [ ]:
df

In [24]:
df.to_sql(name='Flat_for_Sale', con=conn, if_exists='replace')['sqrmeter']

TypeError: 'int' object is not subscriptable

In [36]:
df[df['sqrmeter']=='inwestycji5']

Empty DataFrame
Columns: [index, title, price, price_per_m2, sqrmeter, rooms, floor, page, street, location, max_floor, RefreshYearWeek, link]
Index: []