In [79]:
from datetime import datetime
import sqlite3
import pandas as pd

utils_path = os.path.abspath('/Users/daniel_mac/Desktop/Projects/Budget_app/transaction_analysis_v2/') 
sys.path.append(utils_path)

from utils import queries as qs
import os
import sys

DB_PATH = utils_path + "/db/users_.db"
SCHEMA_PATH = utils_path + "/db/schema.sql"

import yfinance as yf

In [89]:
datetime.today().weekday() < 5

False

In [45]:
conn = sqlite3.connect(DB_PATH, timeout=30)
select_query = f"SELECT * FROM FX_table ORDER BY Date DESC LIMIT 5"
df_last_fx_rates = pd.read_sql_query(select_query, conn)

In [46]:
df_last_fx_rates

   PLN_EUR   PLN_USD                 Date
0      NaN  0.274070  2026-05-17 00:00:00
1      NaN  0.274130  2026-05-16 00:00:00
2  0.23539  0.275167  2026-05-15 00:00:00
3  0.23562  0.276285  2026-05-14 00:00:00
4  0.23562  0.276297  2026-05-14 00:00:00

In [48]:
datetime.weekday(datetime(df_last_fx_rates['Date'][0]))

TypeError: 'str' object cannot be interpreted as an integer

In [75]:
df_last_fx_rates

   PLN_EUR   PLN_USD                 Date
0      NaN  0.274070  2026-05-17 00:00:00
1      NaN  0.274130  2026-05-16 00:00:00
2  0.23539  0.275167  2026-05-15 00:00:00
3  0.23562  0.276285  2026-05-14 00:00:00
4  0.23562  0.276297  2026-05-14 00:00:00

In [78]:
datetime.strptime(df_last_fx_rates['Date'][4].split(' ')[0], "%Y-%m-%d").weekday()

3

In [ ]:
df_fx = yf.download(['PLNUSD=X','PLNEUR=X'], progress=False).Close.round(6).tail(2)
        
        # handling connection issues
        if len(df_fx) == 0:
            raise Exception("No data")
        
        # renaming columns for DB

In [107]:
df_fx = yf.download(['PLNUSD=X','PLNEUR=X'], progress=False).Close.round(6).tail(6)

/var/folders/x8/q__bzqys7yg57g9twpxbqxqm0000gn/T/ipykernel_21087/3106308796.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_fx = yf.download(['PLNUSD=X','PLNEUR=X'], progress=False).Close.round(6).tail(6)

In [118]:
df_fx_ = df_fx *  1.001
df_fx_1 = df_fx *  1.002

In [134]:
df_ = pd.concat([df_fx_,df_fx_1]).sort_index()
df_.rename(columns={'PLNEUR=X':'PLN_EUR','PLNUSD=X':'PLN_USD'}, inplace=True)
df_.reset_index(inplace=True)
df_.drop_duplicates(subset=['Date'], keep='last', inplace=True)
df_.index = df_['Date']
df_

Ticker           Date   PLN_EUR   PLN_USD  Weekend
Date
2026-05-11 2026-05-11  0.236312  0.278270    0.000
2026-05-12 2026-05-12  0.236042  0.278647    0.000
2026-05-13 2026-05-13  0.235490  0.276646    0.000
2026-05-14 2026-05-14  0.235881  0.276633    0.000
2026-05-15 2026-05-15  0.235861  0.275717    0.000
2026-05-17 2026-05-17       NaN  0.274618    1.002

KeyError: Index(['Date'], dtype='object')

In [132]:
df_

Ticker       PLN_EUR   PLN_USD  Weekend
Date
2026-05-11  0.236076  0.277993    0.000
2026-05-11  0.236312  0.278270    0.000
2026-05-12  0.235807  0.278369    0.000
2026-05-12  0.236042  0.278647    0.000
2026-05-13  0.235255  0.276370    0.000
2026-05-13  0.235490  0.276646    0.000
2026-05-14  0.235645  0.276357    0.000
2026-05-14  0.235881  0.276633    0.000
2026-05-15  0.235625  0.275442    0.000
2026-05-15  0.235861  0.275717    0.000
2026-05-17       NaN  0.274344    1.001
2026-05-17       NaN  0.274618    1.002